### PR TITLE
Add Events OnSysKeyPress / -Release

### PR DESCRIPTION
**Pull request by dnlmlr**
Add support for the winapi WM_SYSKEYUP & WM_SYSKEYDOWN events, as described in #186

### CODE REVIEW

**Comment by dnlmlr** [comment]
Not sure if a better description should be added. I would think that the people who might use the `OnSysKey*` Events know what they are, or at least know where to find the docs.

**Comment by dnlmlr** [comment]
Wrong commit email -_-

**Review by gabdube — APPROVED** [review]
Looks good

**Comment by gabdube** [comment]
The doc is fine. If someone use native-windows-gui, I assume they are somewhat familiar with how Windows works.

**Pull request merged**
